trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  Major: '1'
  Minor: '0'
  Patch: '0'

steps:
  - task: DotNetCoreCLI@2
    displayName: Pack NuGet Package
    inputs:
      command: 'pack'
      packagesToPack: '*.csproj'
      includesymbols: false
      versioningScheme: 'byPrereleaseNumber'
      majorVersion: '1'
      minorVersion: '0'
      patchVersion: '0'
  - task: NuGetCommand@2
    displayName: Push to nuget.org
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
      nuGetFeedType: 'external'
      publishFeedCredentials: 'aleexnlNugetOrg'
  - task: NuGetCommand@2
    displayName: Push to github.com
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
      nuGetFeedType: 'external'
      publishFeedCredentials: 'Aleexnl''s GitHub NuGet'