trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  Major: '1'
  Minor: '0'
  Patch: '0'

steps:
  - task: DotNetCoreCLI@2
    displayName: Pack NuGet Package
    inputs:
      command: 'pack'
      packagesToPack: '*.csproj'
      includesymbols: false
      versioningScheme: 'byPrereleaseNumber'
      majorVersion: '1'
      minorVersion: '0'
      patchVersion: '0'
  - task: DotNetCoreCLI@2
    displayName: Push to Feed
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: 'bbb6dbfb-a03d-4eea-92dd-f7174e28638e/514d41be-a375-44cc-8c3e-e3460848e3c0'
  - task: NuGetCommand@2
    displayName: Push to nuget.org
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
      nuGetFeedType: 'external'
      publishFeedCredentials: 'aleexnlNugetOrg'