# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  Major: '1'
  Minor: '0'
  Patch: '0'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Build Project'
  inputs:
    command: 'build'
- task: NuGetCommand@2
  displayName: 'NuGet Pack'
  inputs:
    command: 'pack'
    packagesToPack: '*.csproj'
    versioningScheme: 'byPrereleaseNumber'
    majorVersion: '$(Major)'
    minorVersion: '$(Minor)'
    patchVersion: '$(Patch)'
- task: NuGetAuthenticate@1
  displayName: 'NuGet Authenticate'
- task: NuGetCommand@2
  displayName: 'Push to Feed'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'a1bc0bdf-5f73-4d81-93af-f2ca6a57ea3b'
    allowPackageConflicts: true