# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  Pack&Publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Pack
        run: dotnet pack

      - name: Authenticate in github.com
        run: dotnet nuget add source --username aleexnl --password ${{ secrets.PUBLISH_PACKAGE_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/aleexnl/index.json"

      - name: Push to github.com
        run: dotnet nuget push "*.nupkg"  --api-key ${{ secrets.PUBLISH_PACKAGE_TOKEN }} --source "github"
